name: Scala Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: sbt
      - uses: sbt/setup-sbt@v1
      - name: Run tests (excluding capstone & mapexercise)
        run: sbt "problem1/test" "problem2/test" "problem3/test" "problem4/test" "problem5/test" "problem6/test" "problem7/test" "problem8/test"
